name: Create Ebook

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - uses: docker://pandoc/core:latest
        with:
          args: >-
            wisdom.md
            --metadata title="Merlin's Wisdom Project"
            --metadata author="Merlin Mann"
            -o wisdom.epub
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: ebook
          path: wisdom.epub
            
            
            
