name: Create Ebook

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - name: prep md for pandoc
        id: cleanup
        run: |
          sed -i 's/\/i\//.\/i\//g' wisdom.md                             # Add a . before /i/ paths so pandoc can find them
          sed --regexp-extended 's/<img(.+)">/<img\1"\/>/g' wisdom.md     # Self-close the image tags, pandoc whines if we have unclosed img tags
      - uses: docker://pandoc/core:latest
        with:
          args: >-
            wisdom.md
            --metadata title="Merlin's Wisdom Project"
            --metadata author="Merlin Mann"
            -o wisdom.epub
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: ebook
          path: wisdom.epub
            
            
            
